-- 코드를 입력하세요
/*SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND
H.START_DATE BETWEEN "2022-10-01" AND "2022-10-31"
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;*/

/*SELECT C.CAR_ID, H.START_DATE
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE C.CAR_TYPE = '세단' AND
DATE_FORMAT(H.START_DATE,"%Y-%m-%d") BETWEEN "2022-10-01" AND "2022-10-31"
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;*/

SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE C.CAR_ID = H.CAR_ID AND
 C.CAR_TYPE = '세단' AND
 DATE_FORMAT(H.START_DATE,"%Y-%m") = '2022-10'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC;


/*SELECT C.CAR_ID, H.START_DATE
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE C.CAR_ID = H.CAR_ID AND
 C.CAR_TYPE = '세단'

ORDER BY H.START_DATE ASC;*/