-- 코드를 입력하세요
SELECT U.USER_ID, U.NICKNAME, 
 CONCAT(U.CITY,' ',U.STREET_ADDRESS1,' ',U.STREET_ADDRESS2) AS 전체주소, 
 CONCAT(LEFT(TLNO,3),'-',(SUBSTR(TLNO,4,4)),'-',RIGHT(TLNO,4)) AS 전화번호
FROM USED_GOODS_BOARD B, USED_GOODS_USER U
WHERE B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY U.USER_ID DESC;

/*SELECT B.BOARD_ID, B.WRITER_ID
FROM USED_GOODS_BOARD B
ORDER BY B.WRITER_ID DESC;*/