-- 코드를 입력하세요
SELECT H.CAR_ID, 
 CASE 
  WHEN MAX('2022-10-16' BETWEEN H.START_DATE AND H.END_DATE)
    THEN '대여중'
    ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC;

/*SELECT H.CAR_ID, H.START_DATE, H.END_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ORDER BY H.CAR_ID DESC;*/